services:
  app:
    container_name: measureAi-api-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: docker
      DB_NAME: measureAI
      DATABASE_URL: "postgresql://postgres:docker@postgres:5432/measure-ai?schema=public"
      WAIT_HOSTS: postgres:5432
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - app-network

  postgres:
    container_name: measureAi-api-sp-pg
    hostname: postgres
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: measureAI
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
